temp_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from userapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView, name='home'),
    path('users/', include('userapp.urls')),
    path('article/', include('articleapp.urls')),
    path('fast_test/', include('fast_test.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from userapp import views
from .views import UserCreateView, UserDetailView, UserDeleteView, UserUpdateView

app_name = "userapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='userapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', UserCreateView.as_view(), name='create'),
    path('update/<int:pk>', UserUpdateView.as_view(),name='update'),
    path('detail/<int:pk>', UserDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', UserDeleteView.as_view(), name='delete'),

    path('', views.HomeView, name='home'),

]

userapp/models.py
from django.db import models
from pygments.lexers import get_all_lexers


LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
SKILLS = [('python', 'python'), ('javascript', 'javascript'), ('AWS', 'AWS'), ('Django', 'Django')]
SUPPORT_CHOICES = [('서버 개발비', 'server_pay'), ('AWS 크레딧', 'aws_credit'), ('IDE 지원', 'ide'), ('라이센스 지원', 'license')]


# Create your models here.
class DBUser(models.Model):
    email = models.EmailField(null=False)
    password = models.CharField(max_length=1000, null=False)
    nickname = models.CharField(max_length=100, null=False)
    img = models.ImageField(null=True)
    bio = models.CharField(max_length=1000)


class DBDeveloper(DBUser):
    language = models.CharField(choices=LANGUAGE_CHOICES, default='python', max_length=100)
    skill = models.CharField(choices=SKILLS, default='python', max_length=100)


class DBSupporter(DBUser):
    can_support = models.CharField(choices=SUPPORT_CHOICES, default='None', max_length=100, null=True)
    will_support = models.CharField(choices=SUPPORT_CHOICES, default='None', max_length=100, null=True)


class DBPlanner(DBUser):
    item = models.CharField(default='None', max_length=100, null=False)

userapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class UserUpdateForm(UserCreationForm):
    def __init__(self, *args,**kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

userapp/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from userapp.decorators import account_ownership_required
from userapp.forms import UserUpdateForm

has_ownership = [login_required, account_ownership_required]
#
# classes tempView(View):
#     params = json.loads(request.body.decode('utf-8'))
#     id = params['id']
#     password = params['password']
#
#     result = User.objects.all()
#     # 쿼리셋은 for문을 통해 꺼내야함
#     result[0]['username']
#     # result = User.objects.values()
#     #valuse() : 단일객체(row)에 대해서만 가능
#     # result[0]['username']
#
#     result = User.objects.get(pk=1).valuse()
#
#     # 필터링을 해줄 때, 변수를 만들어서 딕셔너리로 만듬
#     user_name = result.username
#     user_nickname = result.nickname
#
#     user = {'user_name': user_name, 'user_nickname':user_nickname}
#     return  JsonResponse({"result": user}) #직렬화
#

class UserCreateView(CreateView):
    # def get(self,request):
    #     return render()
    #
    # def post(self,request):
    #     return render()

    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('userapp:login')
    template_name = 'userapp/create.html'



class UserDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'userapp/detail.html'



@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('userapp:detail')
    template_name = 'userapp/update.html'

@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class UserDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('userapp:login')
    template_name = 'userapp/delete.html'


def HomeView(request):
    return render(request, 'main.html')

userapp/templates/userapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align:center;max-width: 500px; margin: 4rem auto;">
       <div class="mb-4">
           <h4>회원가입</h4>
       </div>
        <form action="{% url 'userapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}

            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

userapp/templates/userapp/delete.html
{% extends 'base.html' %}


{% block content %}

    <div style="text-align:center;max-width: 500px; margin: 4rem auto;">
       <div class="mb-4">
           <h4>정말로 계정 지울거에요?</h4>
       </div>
        <form action="{% url 'userapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

userapp/templates/userapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div style="text-align: center; max-width:700px; margin: 4rem auto;">
{#    로그인한사람의 페이지와 현제 페이지의 사람이 같다면#}
    {%if target_user == user %}
        {#    현재 유저가 설정한 프로필이 있다면#}
        {% if target_user.profile %}
            {#프로필 사진#}
            <img src="{{ target_user.profile.image.url }}" alt="" style="height:12rem; width:12rem; border-radius:20rem; margin-bottom:2rem; object-fit: cover;">

            <h4 style="margin-bottom:3rem;">
            {#프로필메세지#}
            {{ target_user.profile.message }}
                <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                    <h6>
                        메세지 수정
                    </h6>
                </a>
            </h4>
        {% else %}
            <a href="{% url 'profileapp:create' %}">
            <h5>
                개인프로필 만들기
            </h5>
        </a>
        {% endif %}

        {#회원정보 수정#}
        <a href="{% url 'userapp:update' pk=target_user.pk %}">
            <p>
                회원정보수정
           </p>
        </a>
        <a href="{% url 'userapp:delete' pk=user.pk %}">
            <p>
                회원탈퇴
            </p>
        </a>

{#        다른사름의 계정을 볼 때#}
    {% else %}
        {% if user.profile %}
            <img src="{{ user.profile.image.url }}" alt=""
                 style="height:12rem; width:12rem; border-radius:20rem; margin-bottom:2rem; object-fit: cover;">
            {{ user.profile.message }}
        {% else %}
        <h2>
            설정된 프로필이 없습니다.
        </h2>
        {% endif %}
    {% endif %}
    </div>
</div>

{% endblock %}

userapp/templates/userapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div>
      <h4>로그인</h4>
      </div>
      <div>
        <form action="" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

userapp/templates/userapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align:center;max-width: 500px; margin: 4rem auto;">
       <div class="mb-4">
           <h4>정보 수정</h4>
       </div>
        <form action="{% url 'userapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}