temp_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from userapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView, name='home'),
    path('users/', include('userapp.urls')),
    path('article/', include('articleapp.urls')),
    path('fast_test/', include('fast_test.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from userapp import views
from .views import UserCreateView, UserDetailView, UserDeleteView, UserUpdateView

app_name = "userapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='userapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', UserCreateView.as_view(), name='create'),
    path('update/<int:pk>', UserUpdateView.as_view(),name='update'),
    path('detail/<int:pk>', UserDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', UserDeleteView.as_view(), name='delete'),

    path('', views.HomeView, name='home'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}


<body>
    {% include 'header.html' %}

    <div style="padding-top: 6rem">
        {% block content %}
        {% endblock %}

        <hr>
        {% include 'footer.html' %}
    </div>
</body>


</html>

templates/footer.html
<div class="project9_footer">
    <div class="project9_footer_button">
        <a href="https://github.com/KEEMSY">
            <span>GITHUB</span>
        </a>
    </div>

    <div style="margin-top: 1rem;">
        <h6 class="logo">TemProject</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Temp_PROJECT</title>

    <!--BOOTSTRAP LINK    -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!--DEFAULT CSS    -->
    <link rel="stylesheet" type="text/css " href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css " href="{% static 'css/header.css' %}">
    <link rel="stylesheet" type="text/css " href="{% static 'css/main.css' %}">

    <!--GOOGLE FONT    -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">

    <!--JS    -->
    <script src="{% static 'js/main_banner.js' %}"></script>
</head>

templates/header.html
<div class="fixed_header">
    <div style="display: block" >
        <div class="upper_navbar">
            <a href="">
                <span> 고객센터 </span>
            </a>
            <a href="">
                <span> 마이페이지 </span>
            </a>
            <a href="{% url 'userapp:login' %}?next={{ request.path }}">
                <span> 로그인 </span>
            </a>
        </div>
        <div class="lower_navbar">
            <div class="lower_navbar_left">
                <a href="{% url "userapp:home" %}">
                    <h1 class="logo">TemProject</h1>
                </a>
            </div>
            <div class="lower_navbar_right">
                <a href="{% url 'userapp:home' %}">
                    <span> MAIN </span>
                </a>
                <a href="" class="project9_header_nav">
                    <span> CAREER </span>
                </a>
                <a href="{% url 'userapp:create' %}" class="project9_header_nav">
                    <span> COMMUNITY </span>
                </a>
                <a href="{% url 'userapp:logout' %}?next={{ request.path }}" class="project9_header_nav">
                    <span> SEARCH </span>
                </a>
            </div>
        </div>
    </div>
</div>

templates/main.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="notice_bar">
        <a href="">
            <span> [공지] 피드백하고 공짜치킨먹자! </span>
        </a>
    </div>
    <div>
        <div class="main_banner">
            <div class="slidebox">
                <input type="radio" name="slide" id="slide01" checked>
                <input type="radio" name="slide" id="slide02" >
                <input type="radio" name="slide" id="slide03" >
                <input type="radio" name="slide" id="slide04" >
                <ul class="slide_list">
                    <li class="slide_items">
                        <div>
                            <label for="slide04" class="left"></label>
                            <label for="slide02" class="right"></label>
                            <a><div style="width: 100%; height: 25vw; max-height: 30rem; background-color: green"> 공지사항 </div></a>
                        </div>
                    </li>
                    <li class="slide_items">
                        <div>
                            <label for="slide01" class="left"></label>
                            <label for="slide03" class="right"></label>
                            <a><div style="width: 100%; height: 25vw; max-height: 30rem; background-color: lightskyblue"> 알리미:1일1커밋 </div></a>
                        </div>
                    </li>
                    <li class="slide_items">
                        <div>
                            <label for="slide02" class="left"></label>
                            <label for="slide04" class="right"></label>
                            <a><div style="width: 100%; height: 25vw; max-height: 30rem; background-color:darkturquoise"> 알리미:1일 1문제 </div></a>
                        </div>
                    </li>
                    <li class="slide_items">
                        <div>
                            <label for="slide03" class="left"></label>
                            <label for="slide01" class="right"></label>
                            <a><div style="width: 100%; height: 25vw; max-height: 30rem; background-color: darkorange"> 배너4 </div></a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main_content">
            <div class="main_header">
                <div class="main_header_wrapper">
                    <div class="main_header_content">
                        <div class="main_header_img" style="background-color: paleturquoise">

                        </div>
                        <div class="main_header_title">
                            <span>인기태그</span>
                        </div>
                    </div>
                    <div class="main_header_content">
                        <div class="main_header_img" style="background-color: mediumpurple">

                        </div>
                        <div class="main_header_title">
                            <span>미해결문제</span>
                        </div>
                    </div>
                    <div class="main_header_content">
                        <div class="main_header_img" style="background-color: lavender">

                        </div>
                        <div class="main_header_title">
                            <span>채용공고</span>
                        </div>
                    </div>
                    <div class="main_header_content">
                        <div class="main_header_img" style="background-color: black">

                        </div>
                        <div class="main_header_title">
                            <span>랭킹</span>
                        </div>
                    </div>
                    <div class="main_header_content">
                        <div class="main_header_img" style="background-color: khaki">

                        </div>
                        <div class="main_header_title">
                            <span>공지사항</span>
                        </div>
                    </div>
                </div>

            </div>
            <div class="main_article">
                <div class="main_content_wrapper">
                    <div class="main_new_post">
                        <div class="main_post_title">
                            <span>HOT POSTS</span>
                        </div>
                        <div class="main_post_sub_title">
                            <span>인기 게시글</span>
                        </div>
                        <div class="main_posts">
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div style="text-align: center">
                            <button>
                                <span>더보기</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="temp_banner">
                {#            문제풀이 사이트로 가는 배너 공간#}
                <h2>프로그래머스</h2>
                <h2>백준 </h2>
            </div>

            <div class="main_article">
                <div class="main_content_wrapper">
                    <div class="main_new_post">
                        <div class="main_post_title">
                            <span>NEW POSTS</span>
                        </div>
                        <div class="main_post_sub_title">
                            <span>최신 게시글</span>
                        </div>
                        <div class="main_posts">
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="main_post">
                                <a href="">
                                    <div class="main_post_img">

                                    </div>
                                    <div class="main_post_content">
                                        <div class="main_post_content_title">
                                            <span>임시 제목</span>

                                        </div>
                                        <div class="main_post_content_content">
                                            <span>임시 내용</span>

                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div style="text-align: center">
                            <button>
                                <span>더보기</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>

{% endblock %}